name: Deployment 2
on:
    push:
        branches:
            - main
    pull_request:
        branches: -main

jobs:
    deployment:
        strategy:
            matrix:
                node-version: [14, 16]
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Install NodeJs
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install deps
              run: pnpm install
            - name: Test app
              run: pnpm test
            - name: Lint code
              run: pnpm lint
            - name: Build App
              run: pnpm build
